In [1]:
import pandas as pd

PATH = "run/accuracy/datasets/IMDB_385samples.csv"

df = pd.read_csv("tiff_results/predictions_abhilash88_roberta-sentimentic.csv")

In [2]:
df.head()

df.columns

Index(['original_csv_row_index', 'ground_truth_sentiment',
       'predicted_sentiment'],
      dtype='object')

In [3]:

# 2. Rename
df = df.rename(columns={
    "predicted_sentiment": "roberta-sentimentic-125m",
    "ground_truth_sentiment": "label"
})


df.columns

Index(['original_csv_row_index', 'label', 'roberta-sentimentic-125m'], dtype='object')

In [5]:
df = df.rename(columns={
    "id": "row_id"
})


df.columns

Index(['row_id', 'label', 'roberta-sentimentic-125m'], dtype='object')

In [6]:
df.to_csv(PATH, index=False)

In [8]:
tiny_df = pd.read_csv("tiff_results/predictions_Harsha901_tinybert-imdb-sentiment-analysis-model.csv")

In [9]:
tiny_df = tiny_df.drop(columns=["ground_truth_sentiment"])

tiny_df.head()

   original_csv_row_index predicted_sentiment
0                   33553            negative
1                    9427            positive
2                     199            negative
3                   12447            positive
4                   39489            negative

In [10]:
tiny_df = tiny_df.rename(columns={
    "predicted_sentiment": "tinybert-imdb-15m",
    "original_csv_row_index": "row_id"  
})

tiny_df.head()

   row_id tinybert-imdb-15m
0   33553          negative
1    9427          positive
2     199          negative
3   12447          positive
4   39489          negative

In [11]:
merged = pd.merge(df,  tiny_df, on="row_id")

merged.head()

   row_id     label roberta-sentimentic-125m tinybert-imdb-15m
0   33553  positive                 negative          negative
1    9427  positive                 positive          positive
2     199  negative                 negative          negative
3   12447  positive                 positive          positive
4   39489  negative                 negative          negative

In [12]:
df = merged

df.head()

   row_id     label roberta-sentimentic-125m tinybert-imdb-15m
0   33553  positive                 negative          negative
1    9427  positive                 positive          positive
2     199  negative                 negative          negative
3   12447  positive                 positive          positive
4   39489  negative                 negative          negative

In [13]:
df.to_csv(PATH, index=False)

In [14]:
lla_df = pd.read_csv("tiff_results/predictions_llama3.1_70b.csv")


lla_df.head()

lla_df = lla_df.drop(columns=["ground_truth_sentiment"])

lla_df.head()

lla_df = lla_df.rename(columns={
    "predicted_sentiment": "llama-3.1-70b-it",
    "original_csv_row_index": "row_id"
})

lla_df.head()

merged = pd.merge(df, lla_df, on="row_id")

merged.head()

,row_id,label,roberta-sentimentic-125m,tinybert-imdb-15m,llama-3.1-70b-it
0,33553,positive,negative,negative,positive
1,9427,positive,positive,positive,positive
2,199,negative,negative,negative,negative
3,12447,positive,positive,positive,positive
4,39489,negative,negative,negative,negative

In [15]:
df = merged

df.to_csv(PATH, index=False)

In [17]:
dis_df = pd.read_csv("tiff_results/predictions_lvwerra_distilbert-imdb.csv")


dis_df = dis_df.drop(columns=["ground_truth_sentiment"])



dis_df = dis_df.rename(columns={
    "predicted_sentiment": "distilbert-imdb-67m",
    "original_csv_row_index": "row_id"
})


merged = pd.merge(df, dis_df, on="row_id")

merged.head()

,row_id,label,roberta-sentimentic-125m,tinybert-imdb-15m,llama-3.1-70b-it,distilbert-imdb-67m
0,33553,positive,negative,negative,positive,negative
1,9427,positive,positive,positive,positive,positive
2,199,negative,negative,negative,negative,negative
3,12447,positive,positive,positive,positive,positive
4,39489,negative,negative,negative,negative,negative

In [18]:
df = merged

df.to_csv(PATH, index=False)

In [19]:
import pandas as pd

df = pd.read_csv(PATH)

df.columns

Index(['row_id', 'label', 'roberta-sentimentic-125m', 'tinybert-imdb-15m',
       'llama-3.1-70b-it', 'distilbert-imdb-67m'],
      dtype='object')

In [23]:
df["roberta-sentimentic-125m"].groupby(df["roberta-sentimentic-125m"]).size()
df['tinybert-imdb-15m'].groupby(df['tinybert-imdb-15m']).size()
df['distilbert-imdb-67m'].groupby(df['distilbert-imdb-67m']).size()
df["llama-3.1-70b-it"].groupby(df["llama-3.1-70b-it"]).size()

llama-3.1-70b-it
negative    205
positive    180
Name: llama-3.1-70b-it, dtype: int64