In [1]:
import pandas as pd

PATH = "run/accuracy/datasets/ag_news.csv"

df = pd.read_csv("tiff_results/topic_predictions_llama2_7b.csv")

In [2]:
df.head()

df.columns

Index(['original_jsonl_row_index', 'ground_truth_topic', 'predicted_topic',
       'title', 'description'],
      dtype='object')

In [3]:

# 2. Rename
df = df.rename(columns={
    "predicted_topic": "llama-2-7b-it",
    "ground_truth_topic": "label"
})


df.columns

Index(['original_jsonl_row_index', 'label', 'llama-2-7b-it', 'title',
       'description'],
      dtype='object')

In [5]:

# 3. Reorder
new_order = ['original_jsonl_row_index', "label", "title", "description", "llama-2-7b-it"]  # specify exact order
df = df[new_order]

df.columns

Index(['original_jsonl_row_index', 'label', 'title', 'description',
       'llama-2-7b-it'],
      dtype='object')

In [6]:
df.to_csv(PATH, index=False)

In [7]:
lla_70b_df = pd.read_csv("tiff_results/topic_predictions_llama3_1_70b.csv")

lla_70b_df.columns

Index(['original_jsonl_row_index', 'ground_truth_topic', 'predicted_topic',
       'title', 'description'],
      dtype='object')

In [8]:
lla_70b_df = lla_70b_df.drop(columns=["ground_truth_topic", "title", "description"])

lla_70b_df.head()

   original_jsonl_row_index  predicted_topic
0                         0                3
1                         1                4
2                         2                4
3                         3                4
4                         4                1

In [9]:
lla_70b_df = lla_70b_df.rename(columns={
    "predicted_topic": "llama-3.1-70b-it"
})

lla_70b_df.head()

   original_jsonl_row_index  llama-3.1-70b-it
0                         0                 3
1                         1                 4
2                         2                 4
3                         3                 4
4                         4                 1

In [10]:
merged = pd.merge(df,  lla_70b_df, on="original_jsonl_row_index")

merged.head()

,original_jsonl_row_index,label,title,description,llama-2-7b-it,llama-3.1-70b-it
0,0,3,Fears for T N pension after talks,Unions representing workers at Turner Newall...,4,3
1,1,4,The Race is On: Second Private Team Sets Launc...,"SPACE.com - TORONTO, Canada -- A second\team o...",4,4
2,2,4,Ky. Company Wins Grant to Study Peptides (AP),AP - A company founded by a chemistry research...,4,4
3,3,4,Prediction Unit Helps Forecast Wildfires (AP),AP - It's barely dawn when Mike Fitzpatrick st...,4,4
4,4,4,Calif. Aims to Limit Farm-Related Smog (AP),AP - Southern California's smog-fighting agenc...,4,1

In [11]:
df = merged

df.head()

,original_jsonl_row_index,label,title,description,llama-2-7b-it,llama-3.1-70b-it
0,0,3,Fears for T N pension after talks,Unions representing workers at Turner Newall...,4,3
1,1,4,The Race is On: Second Private Team Sets Launc...,"SPACE.com - TORONTO, Canada -- A second\team o...",4,4
2,2,4,Ky. Company Wins Grant to Study Peptides (AP),AP - A company founded by a chemistry research...,4,4
3,3,4,Prediction Unit Helps Forecast Wildfires (AP),AP - It's barely dawn when Mike Fitzpatrick st...,4,4
4,4,4,Calif. Aims to Limit Farm-Related Smog (AP),AP - Southern California's smog-fighting agenc...,4,1

In [12]:
df.to_csv(PATH, index=False)

In [ ]:
phi_df = pd.read_csv("tiff_results/topic_predictions_phi3_3_8b.csv")


phi_df.head()

phi_df = phi_df.drop(columns=["ground_truth_topic", "title", "description"])

phi_df.head()

phi_df = phi_df.rename(columns={
    "predicted_topic": "Phi-3-Mini-128K-it"
})

phi_df.head()

df = pd.merge(df, phi_df, on="original_jsonl_row_index")

df.head()

#

,original_jsonl_row_index,label,title,description,llama-2-7b-it,llama-3.1-70b-it,Phi-3-Mini-128K-it
0,0,3,Fears for T N pension after talks,Unions representing workers at Turner Newall...,4,3,3
1,1,4,The Race is On: Second Private Team Sets Launc...,"SPACE.com - TORONTO, Canada -- A second\team o...",4,4,4
2,2,4,Ky. Company Wins Grant to Study Peptides (AP),AP - A company founded by a chemistry research...,4,4,4
3,3,4,Prediction Unit Helps Forecast Wildfires (AP),AP - It's barely dawn when Mike Fitzpatrick st...,4,4,4
4,4,4,Calif. Aims to Limit Farm-Related Smog (AP),AP - Southern California's smog-fighting agenc...,4,1,4

In [14]:
df.to_csv(PATH, index=False)

In [15]:
tiny_df = pd.read_csv("tiff_results/topic_predictions_tinyllama_1_1b.csv")


tiny_df = tiny_df.drop(columns=["ground_truth_topic", "title", "description"])

tiny_df = tiny_df.rename(columns={
    "predicted_topic": "TinyLlama-1.1B-it"
})


df = pd.merge(df, tiny_df, on="original_jsonl_row_index")

df.head()

,original_jsonl_row_index,label,title,description,llama-2-7b-it,llama-3.1-70b-it,Phi-3-Mini-128K-it,TinyLlama-1.1B-it
0,0,3,Fears for T N pension after talks,Unions representing workers at Turner Newall...,4,3,3,0
1,1,4,The Race is On: Second Private Team Sets Launc...,"SPACE.com - TORONTO, Canada -- A second\team o...",4,4,4,0
2,2,4,Ky. Company Wins Grant to Study Peptides (AP),AP - A company founded by a chemistry research...,4,4,4,1
3,3,4,Prediction Unit Helps Forecast Wildfires (AP),AP - It's barely dawn when Mike Fitzpatrick st...,4,4,4,1
4,4,4,Calif. Aims to Limit Farm-Related Smog (AP),AP - Southern California's smog-fighting agenc...,4,1,4,1

In [16]:
df.to_csv(PATH, index=False)

In [17]:
import pandas as pd

df = pd.read_csv("run/accuracy/datasets/ag_news.csv")

df.columns

Index(['original_jsonl_row_index', 'label', 'title', 'description',
       'llama-2-7b-it', 'llama-3.1-70b-it', 'Phi-3-Mini-128K-it',
       'TinyLlama-1.1B-it'],
      dtype='object')

In [ ]:
# df["label"].groupby(df["label"]).size()
# df["llama-2-7b-it"].groupby(df["llama-2-7b-it"]).size()
# df["llama-3.1-70b-it"].groupby(df["llama-3.1-70b-it"]).size()
# df["Phi-3-Mini-128K-it"].groupby(df["Phi-3-Mini-128K-it"]).size()
# df["TinyLlama-1.1B-it"].groupby(df["TinyLlama-1.1B-it"]).size()

llama-2-7b-it
0     155
1     725
2     167
3     119
4    6434
Name: llama-2-7b-it, dtype: int64

In [ ]:
# for index, row in df.iterrows():
#     if row["bloomz-1b7"] == "unknown":
#         df.at[index, "bloomz-1b7"] = "neutral"

# df["bloomz-1b7"].unique()

array(['contradiction', 'entailment', 'neutral'], dtype=object)