In [ ]:
import pandas as pd

PATH = "run/accuracy/datasets/SNLI.csv"

df = pd.read_csv("tiff_results/nli_predictions_gemma3_4b.csv")

In [3]:
df.head()

df.columns

Index(['original_parquet_row_index', 'ground_truth_label', 'predicted_label',
       'raw_model_output', 'premise', 'hypothesis'],
      dtype='object')

In [4]:
# 1. Drop
df = df.drop(columns=["raw_model_output"])

df.columns

Index(['original_parquet_row_index', 'ground_truth_label', 'predicted_label',
       'premise', 'hypothesis'],
      dtype='object')

In [5]:

# 2. Rename
df = df.rename(columns={
    "predicted_label": "gemma-3-4b-it",
    "ground_truth_label": "label"
})


df.columns

Index(['original_parquet_row_index', 'label', 'gemma-3-4b-it', 'premise',
       'hypothesis'],
      dtype='object')

In [6]:

# 3. Reorder
new_order = ['original_parquet_row_index', "label", "premise", "hypothesis", "gemma-3-4b-it"]  # specify exact order
df = df[new_order]

df.columns

Index(['original_parquet_row_index', 'label', 'premise', 'hypothesis',
       'gemma-3-4b-it'],
      dtype='object')

In [10]:
df.to_csv(PATH, index=False)

In [17]:
blo_df = pd.read_csv("tiff_results/nli_predictions_gouranshitera_bloomz-1b7.csv")

In [18]:
blo_df = blo_df.drop(columns=["ground_truth_label", "raw_model_output", "premise", "hypothesis"])

blo_df.head()

   original_parquet_row_index predicted_label
0                        6252   contradiction
1                        4684   contradiction
2                        1731   contradiction
3                        4742   contradiction
4                        4521   contradiction

In [19]:
blo_df = blo_df.rename(columns={
    "predicted_label": "bloomz-1b7"
})

blo_df.head()

   original_parquet_row_index     bloomz-1b7
0                        6252  contradiction
1                        4684  contradiction
2                        1731  contradiction
3                        4742  contradiction
4                        4521  contradiction

In [20]:
merged = pd.merge(df,  blo_df, on="original_parquet_row_index")

merged.head()

,original_parquet_row_index,label,premise,hypothesis,gemma-3-4b-it,bloomz-1b7
0,6252,neutral,A kid bored in a train with brown hair and his...,A child is riding the train from New York to B...,neutral,contradiction
1,4684,contradiction,A brown dog and black and white dog run along ...,Two squirrels run after acorns in the grass.,neutral,contradiction
2,1731,neutral,A person in full astronaut suit and gear train...,A female astronaut adjusting to the feeling of...,entailment,contradiction
3,4742,contradiction,An old Indian man dressed in rags sleeps on th...,An old Indian man is dressed up,neutral,contradiction
4,4521,neutral,A bunch of people are standing all together in...,A group of people are planning something.,neutral,contradiction

In [21]:
df = merged

df.head()

,original_parquet_row_index,label,premise,hypothesis,gemma-3-4b-it,bloomz-1b7
0,6252,neutral,A kid bored in a train with brown hair and his...,A child is riding the train from New York to B...,neutral,contradiction
1,4684,contradiction,A brown dog and black and white dog run along ...,Two squirrels run after acorns in the grass.,neutral,contradiction
2,1731,neutral,A person in full astronaut suit and gear train...,A female astronaut adjusting to the feeling of...,entailment,contradiction
3,4742,contradiction,An old Indian man dressed in rags sleeps on th...,An old Indian man is dressed up,neutral,contradiction
4,4521,neutral,A bunch of people are standing all together in...,A group of people are planning something.,neutral,contradiction

In [22]:
df.to_csv(PATH, index=False)

In [26]:
lla_df = pd.read_csv("tiff_results/nli_predictions_llama3_1_70b.csv")


lla_df.head()

lla_df = lla_df.drop(columns=["ground_truth_label", "raw_model_output", "premise", "hypothesis"])

lla_df.head()

lla_df = lla_df.rename(columns={
    "predicted_label": "llama-3.1-70b-it"
})

lla_df.head()

df = pd.merge(df, lla_df, on="original_parquet_row_index")

df.head()

df.to_csv(PATH, index=False)

In [ ]:
df = df.drop(columns=["llama-3.1-70b-it_y"])

df.head()

,original_parquet_row_index,label,premise,hypothesis,gemma-3-4b-it,bloomz-1b7,llama-3.1-70b-it_x
0,6252,neutral,A kid bored in a train with brown hair and his...,A child is riding the train from New York to B...,neutral,contradiction,neutral
1,4684,contradiction,A brown dog and black and white dog run along ...,Two squirrels run after acorns in the grass.,neutral,contradiction,neutral
2,1731,neutral,A person in full astronaut suit and gear train...,A female astronaut adjusting to the feeling of...,entailment,contradiction,entailment
3,4742,contradiction,An old Indian man dressed in rags sleeps on th...,An old Indian man is dressed up,neutral,contradiction,contradiction
4,4521,neutral,A bunch of people are standing all together in...,A group of people are planning something.,neutral,contradiction,neutral

In [29]:
df = df.rename(columns={
    "llama-3.1-70b-it_x": "llama-3.1-70b-it"
})

df.head()

,original_parquet_row_index,label,premise,hypothesis,gemma-3-4b-it,bloomz-1b7,llama-3.1-70b-it
0,6252,neutral,A kid bored in a train with brown hair and his...,A child is riding the train from New York to B...,neutral,contradiction,neutral
1,4684,contradiction,A brown dog and black and white dog run along ...,Two squirrels run after acorns in the grass.,neutral,contradiction,neutral
2,1731,neutral,A person in full astronaut suit and gear train...,A female astronaut adjusting to the feeling of...,entailment,contradiction,entailment
3,4742,contradiction,An old Indian man dressed in rags sleeps on th...,An old Indian man is dressed up,neutral,contradiction,contradiction
4,4521,neutral,A bunch of people are standing all together in...,A group of people are planning something.,neutral,contradiction,neutral

In [30]:
df.to_csv(PATH, index=False)

In [31]:
mis_df = pd.read_csv("tiff_results/nli_predictions_mistral_7b.csv")


mis_df = mis_df.drop(columns=["ground_truth_label", "raw_model_output", "premise", "hypothesis"])



mis_df = mis_df.rename(columns={
    "predicted_label": "Mistral-7B-Instruct"
})


df = pd.merge(df, mis_df, on="original_parquet_row_index")

df.head()

,original_parquet_row_index,label,premise,hypothesis,gemma-3-4b-it,bloomz-1b7,llama-3.1-70b-it,Mistral-7B-Instruct
0,6252,neutral,A kid bored in a train with brown hair and his...,A child is riding the train from New York to B...,neutral,contradiction,neutral,neutral
1,4684,contradiction,A brown dog and black and white dog run along ...,Two squirrels run after acorns in the grass.,neutral,contradiction,neutral,neutral
2,1731,neutral,A person in full astronaut suit and gear train...,A female astronaut adjusting to the feeling of...,entailment,contradiction,entailment,neutral
3,4742,contradiction,An old Indian man dressed in rags sleeps on th...,An old Indian man is dressed up,neutral,contradiction,contradiction,contradiction
4,4521,neutral,A bunch of people are standing all together in...,A group of people are planning something.,neutral,contradiction,neutral,neutral

In [32]:
df.to_csv(PATH, index=False)

In [1]:
import pandas as pd

df = pd.read_csv("run/accuracy/datasets/SNLI.csv")

df.columns

Index(['original_parquet_row_index', 'label', 'premise', 'hypothesis',
       'gemma-3-4b-it', 'bloomz-1b7', 'llama-3.1-70b-it',
       'Mistral-7B-Instruct'],
      dtype='object')

In [7]:
# df["bloomz-1b7"].unique()
df["Mistral-7B-Instruct"].unique()
df["gemma-3-4b-it"].unique()
df["llama-3.1-70b-it"].unique()

array(['neutral', 'entailment', 'contradiction'], dtype=object)

In [4]:
for index, row in df.iterrows():
    if row["bloomz-1b7"] == "unknown":
        df.at[index, "bloomz-1b7"] = "neutral"

df["bloomz-1b7"].unique()

array(['contradiction', 'entailment', 'neutral'], dtype=object)

In [8]:
df.to_csv("run/accuracy/datasets/SNLI.csv", index=False)